<?php

  function cipher_menu() {
    $items['cipher'] = array(
      'title' => 'Cipher Phrase Encrypter',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('cipher_form'),
      'access callback' => TRUE,
      'type' => MENU_NORMAL_ITEM,
    );
    return $items;
  }

  function cipher_form() {
    $form['phrase'] = array(
      '#title' => 'Phrase:',
      '#type' => 'textfield',
      '#description' => t('Please enter your message to be encrypted here.'),
      '#element_validate' => array('phrase_validate'),
      '#required' => TRUE,
    );
  }
