<?php

  function cipher_menu() {
    $items['cipher'] = array(
      'title' => 'Cipher Phrase Encrypter',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('cipher_form'),
      'access callback' => TRUE,
      'type' => MENU_NORMAL_ITEM,
    );
    return $items;
  }

  function cipher_form() {
    $form['phrase'] = array(
      '#title' => 'Phrase:',
      '#type' => 'textfield',
      '#description' => t('Please enter your message to be encrypted here.'),
      '#element_validate' => array('phrase_validate'),
      '#required' => TRUE,
    );
    $form['shift_amount'] = array(
      '#title' => 'Shift Amount:',
      '#type' => 'textfield',
      '#description' => t('Please enter a number between 1-25.'),
      '#element_validate' => array('element_validate_number', 'element_validate_integer_positive', 'element_validate_range'),
      '#required' => TRUE,
    );
    $form['shift_direction'] = array(
      '#title' => 'Right or Left?',
      '#type' => 'textfield',
      '#description' => t('Enter either "right" or "left" to tell the cipher which direction in the alphabet to shift.'),
      '#element_validate' => array('element_validate_direction'),
      '#required' => TRUE,
    );
    $form['submit'] = array(
      '#type' => 'submit',
      '#value' => 'Encrypt Now!',
    );
    return $form;
  }
